version: "3.7"
services:
  echo-client:
    image: jaegertracing/all-in-one:1.31
    ports:
    - "6831:6831/udp"
    - "16686:16686"
    - "14268:14268"
    - "14250:14250"
  nats:
    image: nats:latest
    ports:
      - "4222:4222"    
